### ISSUE TITLE
decorating "columns" with embedded objects

### ISSUE THREAD

**Issue by KorayKirli** [hms-dbmi/encode#109]
If an object is embedded in another one ( In case of Biosample we have Biosource, Modification and Treatment embedded) using it in the columns section puts the whole object in the field. 
<img width="1178" alt="biosamples" src="https://cloud.githubusercontent.com/assets/19821570/17497472/fb660078-5d8f-11e6-8a0c-c1d2052be5c7.png">
If the object is not embedded, only the path is displayed. I tried couple of things on biosample.json like replacing
`    "columns": {
        "biosource": {
            "title": "Biosource"
        }`
with
`    "columns": {
        "biosource.accession": {
            "title": "Biosource"
        }`
or 
`    "columns": {
        "biosource[accession]": {
            "title": "Biosource"
        }`
or
`    "columns": {
        "biosource[\"accession\"]": {
            "title": "Biosource"
        }`
but it did not solve the problem.

Would be great to know how we can put the reference for the item, even if it is embedded.

**Comment by KorayKirli** [comment]
For the time being the issue is solved at the front end level by @carlvitzthum

**Comment by carlvitzthum** [comment]
Made it so the description of an object is cut to the closest word @ 100 characters if the description is > 100 characters long, with '...' appended

**Comment by carlvitzthum** [comment]
Changed collections so that columns will correctly find fields of embedded objects (such as biosample.uuid). Will still default to a description capped @ 100 words if no specific field for an embedded object is given
