### ISSUE TITLE
regex validation of taxon ID not working

### ISSUE THREAD

**Issue by aschroed** [hms-dbmi/encode#11]
The organism.json contains the following property:

"taxon_id": {
            "title": "Taxon ID",
            "description": "The NCBI taxon ID for the organism (e.g. 10090).",
            "type": "string",
            "format": "^[0-9]+$"
        }

However, I was able to create a dummy organism (cow) with a taxon_id of 'atev'

**Comment by KorayKirli** [comment]
"pattern" was written as "format"
