### ISSUE TITLE
Document Permissions

### ISSUE THREAD

**Issue by j1z0** [hms-dbmi/encode#14]
Permissions are well a bit complicated, create a document to make them easier to understand.

**Comment by KorayKirli** [comment]
The permission for experiment is linked to status, we know consolidated all different types of status under one that is in mixin, and the permission based on status might need some change. If problematic, we can create new status types again.

**Comment by KorayKirli** [comment]
Some mixins have the 
"permission": "import_items",

some of them are the ones that are generated, like uuid and accession
some are transferred,  like user, lab, creation date
some are there for no obvious reason, like notes

is there are reason why we have this reason, should all mixins have this, or only some?
