### ISSUE TITLE
Identify the mechanism that determines the cardinality of a field

### ISSUE THREAD

**Issue by aschroed** [hms-dbmi/encode#16]
Some fields can only be filled in with a single value.  Others you can add multiple items of the same type.  For example, in Biosample you can only enter a single source and you can add multiple references by repeatedly clicking on the 'Add' button.   

Where in the infrastructure is this type of behavior implemented and controlled?

**Comment by aschroed** [comment]
Is this simply specified by the 'type' field in the json?  If value is 'array' that allows multiple values otherwise it is single value?

And then I believe you can specify the type of things that are allowed in the array using the 'items' stanza and also explicitly set the min and max number of elements in the array with 'minItems' and 'maxItems'.

I think there is something additional when dealing with LD that I still want to look into.

**Comment by j1z0** [comment]
@aschroed - yeah I think you have that all correct. Not sure f you got this but in the item stanza you can specify the exact type of each item in the array, for example if you wanted and array of three items the first being a number and the second two being a string you could use:

```
"items": [
    {
      "type": "number"
    },
    {
      "type": "string"
    },
    {
      "type": "string"
    },
]
```
