### ISSUE TITLE
Define organizational structure of 4DN for award schema

### ISSUE THREAD

**Issue by aschroed** [hms-dbmi/encode#21]
The attached file contains the snippets from the ENCODE-related award.json.  This makes sense for them as they have various phases of the project as well as other projects using the schema (and presumably managed in the same infrastructure).

For 4DN it is not clear to me if there are different phases and whether the different "projects" should be categorized into specific groups (NOFICs, others, imaging, CCC?) and it seems there may be political aspects to this.  

For this reason I want to initially assign this to Burak for his consideration (though I don't see him available as someone to assign issues to).

[award_attribution_snippet.txt](https://github.com/hms-dbmi/encode/files/357460/award_attribution_snippet.txt)

**Comment by burakalver** [comment]
It depends a little bit on where this is used. We would not need project or viewing_group unless we start taking data from other consortia. RFA information is probably good to have in case we need it later. Based on this: https://commonfund.nih.gov/4Dnucleome/FundedResearch, we should have 4 categories:
NOFIC (Nuclear Organization and Function Interdisciplinary Consortium)
Imaging (4DN Imaging Tools)
Nuclear-Bodies (Study of Nuclear Bodies and Compartments)
Nucleomics (Nucleomic Tools)

It is unlikely that this information will be used for anything downstream other than gather statistics about different RFA types.

For permissions, we need items to be
- viewable by lab, or the consortium, or the world.
- editable by lab or frozen.

The information in these award attributions should not be related to permissions.

**Comment by aschroed** [comment]
I've assigned this back to Koray and I to implement based on Burak's comments in the Award schema.
