### ISSUE TITLE
Schema Destroyer types/experiment.py

### ISSUE THREAD

**Issue by aschroed** [hms-dbmi/encode#22]
Added some more pieces to the schema - document.json and experiment.json (note this is a minimal version with only a few fields).

Able to start server and navigate to Users, Awards, Labs - yay!

But not surprisingly when entering localhost:8000/experiments get an object not found page.
If I add back the types/experiment.py file then the server won't start with: ImportError: No module named 'encoded.types.dataset' which makes total sense as there is an import dataset directive in experiment.py but we don't want datasets in the new schema.  Not only that but there seems to be a good deal of code in experiment.py that relies on other classes and code that we may or may not want.

So I guess the question is what is a practical way forward?
- keep building json files and as long as they don't break the start up keep on going though we can't see any of the resulting effects.
- learn how to create (or have Jeremy create minimal type/xxxx.py files) worrying about audits, embedded and other functionality later.
- have Jeremy re-write all of the types files as we need them and as we add the each schema in his loads of spare time (NOT!) 
- something completely different

**Comment by j1z0** [comment]
@aschroed -- I think we discussed a way forward here that appears to be working correct?  Can you close if so, or let me know if there is anything other assistance you require.

**Comment by KorayKirli** [comment]
@j1z0 -- I will try to take care of experiment.py tomorrow, and once I am done I would close the issue.
