### ISSUE TITLE
Add Individual and Human Individual to Schema Destroyer

### ISSUE THREAD

**Issue by aschroed** [hms-dbmi/encode#25]
The current version of Schema Destroyer will start up and load the minimal test data on Users, Labs, Awards, Documents.

The task is to add info to the schema and types to allow loading of 'Human Individual' data.

To Add to encode/src/encoded/schemas/
     individual.json
     human_individual.json 

These should contain the fields that are in the 4DN Metadata Schema document for those particular items.

You can refer to encode/src/encoded/encode_schemas/donor.json and human_donor.json for starting templates.

To Add to encode/src/encoded/types/

individual.py

Refer to  encode/src/encoded/encode_types/donor.py for the encode functionality of the donor type that is analagous to our individual.

To Add to encode/src/encoded/tests/data/inserts/

human_donor.json

Which will have the json that contain test data for human_individuals

Refer to encode/src/encoded/tests/data/old_inserts/

for encode style test data.

**Comment by KorayKirli** [comment]
This part is completed and pushed to Schema Destroyer branch. I will continue with addition of the mouse individual for now.
