### ISSUE TITLE
Property in 'source.json' and web portal behavior inconsistent

### ISSUE THREAD

**Issue by aschroed** [hms-dbmi/encode#29]
Here is the 'name' property in source.json:
<code>
        "name": {
            "comment": "Do not submit, value is auto generated from the title as lower cased and hyphen delimited.",
            "type": "string",
            "pattern": "^[a-z0-9\\-]+$",
            "uniqueKey": true
        },
</code>

However, from what I can tell the value is not auto generated on our beanstalk instance.  I would expect perhaps to see a '@calculated property' in the relevant section of __init.py__ in types directory but no sign of one.  

I don't necessarily want to see this fixed per se but want to confirm that this is not working as indicated by the comment and that the way that one would get this to work would be to make this a calculated property or something of that nature?

**Comment by j1z0** [comment]
discussed in slack... basically you need to overwrite the _update method for your item in src/encoded/types/*
