### ISSUE TITLE
Accession vs UUID

### ISSUE THREAD

**Issue by KorayKirli** [hms-dbmi/encode#35]
I realized that when I create an insert it has to have an UUID, otherwise it fails to load the item. 
In case of accession, it will be created even if it is not given in the insert. It creates different accession numbers every time I load the inserts.

I do not fully understand how these two are managed and connected to each other. 
I wanted to make note of this in case it comes up again.

**Comment by burakalver** [comment]
I believe the answer is: UUID is something assigned by the submitter and allows them to keep referring back to what they submitted. Accession is what we assign on our end. Sounds like a reasonable model that we can keep following. Does this answer the question?

**Comment by aschroed** [comment]
Actually I think UUID is automatically generated and serves as a primary database key.  We will also assign accessions but only to certain Items.  What items we assign accession to should be dictated by perhaps 2 things: 1) what do we want to have persistently trackable by public (and us).  For accessions you can retire an accession and make it secondary to a new primary accession for example - if you merge files into a new larger file.  2) when we feel that a user would like to view a list of things that are 'hard' to name and we don't want to just show them a list of UUIDs - for example it is not straightforward to give a short name to a biosample or experiment but you might want to show all the experiments in an experimentSet.   

Reason 1 should  be the primary driver of deciding which things get accessioned but Reason 2 might be a convenience that maybe won't hurt although could potentially add some overhead regarding tracking accession history for things that really don't need it.

**Comment by aschroed** [comment]
Oh and I believe that Koray's original question had to do more with how these things are automatically generated and managed by the software - and that remains unclear to us.

**Comment by burakalver** [comment]
ok. I got confused about UUID vs. user assigned IDs.

**Comment by KorayKirli** [comment]
I think encode has the accession for objects or collections that are important pieces of encode, like experiments and biosamples, but hard to express with unique names. Instead of the long uuid, they have a nicer version of it. My question was if they should be connected, such that if you have a uuid, it should always correspond to one accession, however I guess this problem was due to usage of inserts as sample data, and will become unimportant once we start using real submission tools.
