### ISSUE TITLE
Embedding objects in classes

### ISSUE THREAD

**Issue by KorayKirli** [hms-dbmi/encode#37]
We do not need to embed the first level objects to the schemas but this does not work for the abstract collection items as fas as I understand.

I will close the issue once I confirm that this is the case.
I assigned people just to make sure that you read this.

**Comment by KorayKirli** [comment]
Strangely if I try to get rid of embedding Lab to User in init.py, it breaks the website

**Comment by j1z0** [comment]
Yes I would assume because at the very least permissions are based on this relationship so it prob should be present. 

Cheers,
Jeremy

**Comment by KorayKirli** [comment]
I see that we need to embed the first level objects also. the problem turns out to be a typo, Linkto instead of linkTo.

If we embed Enzyme_source to Enzyme,   and then embed Enzyme to Experiment, Enzyme source is not accessible to Experiment. I need to embed Enzyme.enzyme_source additionally.
