### ISSUE TITLE
remove object specific js

### ISSUE THREAD

**Issue by j1z0** [hms-dbmi/encode#51]
so default js editing page will "work"

**Comment by j1z0** [comment]
do this in Schema Destroyer branch only

**Comment by carlvitzthum** [comment]
Below are all of the different objects that have unique views

**Definitely remove**
AntibodyLot
Biosample
Donor
Collection
Annotation
PublicationData
Reference
Project
UscsBrowserComposite
Series
Experiment
Image
Pipeline
Publication
Report
Software
TALEN
Target
User

**Don't remove?**
ItemEdit (edit-json, edit, add)
Error
HTTPNotFound
HTTPForbidden
LoginDenied
RenderingError
Portal (impersonate-user)
Item
Matrix
Page
JSONSchema
Search

**Comment by carlvitzthum** [comment]
Object view pages listed as "definitely remove" above (with the exception of collection) are now viewed as Items
