### ISSUE TITLE
Add functionality to profile link on dropdown menu

### ISSUE THREAD

**Issue by carlvitzthum** [hms-dbmi/encode#54]
@j1z0 does this just need to route to /profile/ (or whatever it's called?)

**Comment by j1z0** [comment]
yeah that’s correct.  It’s worth finding where it exists in the code currently,  I think its the <UserActions/> component.

**Comment by carlvitzthum** [comment]
Removed the old User Actions dropdown and added Profile and Impersonate User links to the Account dropdown. The page must auto-refresh (several seconds) before these are added.
