### ISSUE TITLE
Effect of frame=object option of json view

### ISSUE THREAD

**Issue by KorayKirli** [hms-dbmi/encode#66]
Encode help page states the following for ?format=json option.
`
Notice that the experiment objects returned contain only a subset of the properties. These are the properties that the server returns to the web app to render the search results page. To get the full objects back, add &frame=object to the query. 
`

In our case when we look at the experiment object, we see that the following objects are embedded: 
- protocol 
- experiment relation
- lab
- digestion enzyme
- documents

but not the objects
- award (it is a first level object, but not embedded in the class(Experimend))
- submitted by

When the frame=object option is added the following items are not embedded anymore:
- protocol
- lab
- digestion enzyme

These remain embedded
- experiment relation
- documents

It would be great to know what drives this behavior.

**Comment by KorayKirli** [comment]
It turns out when you use frame=object it is using .py types files embedded items to populate. Since we did not embed everything like encode they get smaller. It is not clear to me why award and submitted by not show up, maybe because they are mixin, although documents is also a mixin.

**Comment by KorayKirli** [comment]
Double checked now, object does not get embedded at all. It is just a link. Than concludes the issue

**Comment by carlvitzthum** [comment]
Behavior of embedded objects in facets makes no sense...

**Comment by KorayKirli** [comment]
It got confusing again,
compare 
enzyme vendor in enzyme which is embedded
biosource vendor in biosource which is not embedded

in the ?format=json views, biosource has it embedded but enzyme not

**Comment by carlvitzthum** [comment]
My question: why do the embedded objects differ between `/search/?type=ExperimentHiC&format=JSON` and `/experiments-hic/<ACCESSION>/?format=JSON`?
