### ISSUE TITLE
Publication Datasets

### ISSUE THREAD

**Issue by KorayKirli** [hms-dbmi/encode#72]
Encode had dataset structure, which is also linked from publications. We have that field in publication but there is no dataset schema. 

Are we going to have datasets, or shall I delete that from publication?

**Comment by burakalver** [comment]
Do I remember correctly that in encode, datasets and experiments are almost matching one-to-one? I don't think we need dataset objects. 

And we have a schema for ExperimentSet, right? What is the use case we have in mind for that? Can an experiment be in multiple sets?

I think we can have publications linking an array of experiments or an experiment set.

Does that make sense?
