### ISSUE TITLE
Back to Experiment (from experimend)

### ISSUE THREAD

**Issue by KorayKirli** [hms-dbmi/encode#76]
I renamed experimend to experiment, and got one error.
There is one method in src/encoded/search.py "def search_result_actions"
That checks if doc_types is experiment. This one prevents bin/pserve development.ini to function and drives it to debugging mode. I changed this part of the script to escape this.
I am not sure what that piece of code does, it would be great if you can have a look at that.

**Comment by aschroed** [comment]
Koray and Jeremy both get a taco if we can solve and close this!
