### ISSUE TITLE
non-admin sign in leaves a gap in user drop-down menu

### ISSUE THREAD

**Issue by KorayKirli** [hms-dbmi/encode#78]
Hey @carlvitzthum , You fixed this superimposed signout and settings for the user drop-down for admin. Now if I create a submitter user, and look at the same drop down menu, this time there is a gap, in admin view there is the "impersonate user" field in that gap.
the little things
<img width="205" alt="screen shot 2016-08-04 at 2 56 15 pm" src="https://cloud.githubusercontent.com/assets/19821570/17414629/2112d344-5a54-11e6-9d8d-c0795b65debb.png">

**Comment by carlvitzthum** [comment]
@KorayKirli good catch! I'll fix that up

**Comment by carlvitzthum** [comment]
Should now work correctly for any number of user actions
